[package]
name = "integrity-zero"
version = "0.1.0"
authors = ["Andrea Burza"]
license = "MIT"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
rand = "0.9.2"
ratatui = "0.29.0"
